name: Deploy A Juliana Noronha Rails API to Production

on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploying to Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@master
      - name: Copy files via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key_path: ${{ secrets.SSH_PRIVATE_KEY_PATH }}
          port: ${{ secrets.SSH_PORT }}
          source: "./*"
          target: /home/rails/rails-api/production
      - name: Install dependencies
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          bundler-cache: true
      - name: Backup database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key_path: ${{ secrets.SSH_PRIVATE_KEY_PATH }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker exec rails-api /bin/bash -c 'exec mysqldump --databases ajuliananoronha -uroot -p"${{ secrets.MYSQL_PASSWORD }}"' > /root/backup/a-juliana-noronha-mysql_$(date +"%Y-%m-%d-%H%-M").sql
      - name: Execute DB migrations
        run: bin/rake db:migrate

